### ISSUE TITLE
text_vocab_size for model training

### ISSUE THREAD

**Issue by Lokshaw-Chau** [jasonppy/VoiceCraft#102]
Hi! Thanks for your impressive work!

In the `vocab.txt` file provided in https://huggingface.co/datasets/pyp1/VoiceCraft_RealEdit/blob/main/vocab.txt, it only contains 80 items but in the [training script]( https://github.com/jasonppy/VoiceCraft/blob/master/z_scripts/e830M_ft.sh) the `text_vocab_size` is set to 100. I am wondering why there is a difference?

**Comment by jasonppy** [comment]
Yes, so there are 20 token-embeddings that are not used, for no particular reason

**Comment by Lokshaw-Chau** [comment]
Thanks for your timely reply! I get it.
