### ISSUE TITLE
How to train this model using dual GPU?

### ISSUE THREAD

**Issue by yoesak** [jasonppy/VoiceCraft#103]
Hi I follow how to train the model on README, and I already set 

export CUDA_VISIBLE_DEVICES=0,1

but why my second GPU seems not working while training?

**Comment by yoesak** [comment]
I got error when running e830M.sh 

`RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by yoesak** [comment]
sorry my mistake I forgot to set the WORLD_SIZE, now solved

**Comment by Magauiya** [comment]
@yoesak have you encountered following issue during training: "loss at step <step number> is **nan**, therefore skip this batch"
