### ISSUE TITLE
Highest version of dependent libs/packages?

### ISSUE THREAD

**Issue by martinerk0** [jasonppy/VoiceCraft#108]
I wanted to run this on an Aarch64 computer, which doesn't have all the conda packages built, also with torch 2.2.0 and all latest repos (they need to be build from source anyways). I have 32G of VRAM and it works on few second bits, but anything longer crashes. Is there any reason in instructions you use these particular versions of libraries/packages? Did you try to use latest torch/torchaudio?

**Comment by jasonppy** [comment]
I develop the model under the environment I listed in this github repo. I think most of the time higher versions work.

For example, this setup also work: https://huggingface.co/spaces/pyp1/VoiceCraft_gradio/blob/main/README.md

**Comment by martinerk0** [comment]
I used all the latest versions of the packages/libraries used, and they worked so far, so closing :)
