### ISSUE TITLE
use facebook's pretrained encodec model 

### ISSUE THREAD

**Issue by thivux** [jasonppy/VoiceCraft#144]
i am experimenting voicecraft with another language and i don't want to retrain a custom encodec model for that language. have anyone tried training voicecraft with 8-codebook encodec checkpoint from facebook? how is the result compared to using 4 codebooks?

**Comment by jasonppy** [comment]
From other people's feedback, you don't need to retrain encodec on your target language. Just finetuning the LLM is enough

**Comment by thivux** [comment]
thanks @jasonppy for the info. if i have a large dataset (~5k hours of audio) in my target language (Vietnamese), should i go with fine-tuning the LLM or retrain a new one?

**Comment by jasonppy** [comment]
You could try both
________________________________

**Comment by thivux** [comment]
thank you. closing the issue.

**Comment by justinatbahasa** [comment]
hi @thivux, curious about your results, does by only finetune the trained model with new language is enough? or train new model from scratch is preferable? thanks

**Comment by thivux** [comment]
@justinatbahasa hi, from my experience, finetuning the pretrained checkpoint with a smaller amount of data (400 hours vietnamese + 100 hours english) gave even better results than training from scratch (5k hours vietnamese)

**Comment by justinatbahasa** [comment]
cool! thanks

**Comment by Magauiya** [comment]
Hi @thivux @justinatbahasa ! Do you have any clue why training from scratch gives worse results than finetuning? Have you guys followed the same training scheme as the original paper when you trained from scratch (4 gpus LR=0.01 and had no **"is nan, therefore skip this batch"** issues)?
