### ISSUE TITLE
mfa: command not found

### ISSUE THREAD

**Issue by Sweetapocalyps3** [jasonppy/VoiceCraft#21]
This line of code fails:

os.system(f"mfa align -j 1 --output_format csv {temp_folder} english_us_arpa english_us_arpa {align_temp}")

what 'mfa' should stand for?

Thanks

**Comment by Sweetapocalyps3** [comment]
Ok, got it. It's montreal-forced-aligner and it's missing in the pip requirements section.

**Comment by friendlyFriend4000** [comment]
what have you done to resolve this. I get an error that english_us_arpa model is missing. I am unsure on how to install it properly

**Comment by Ednaordinary** [comment]
> what have you done to resolve this. I get an error that english_us_arpa model is missing. I am unsure on how to install it properly

@friendlyFriend4000 

`mfa model download dictionary english_us_arpa`

model will appear in a subfolder of ~/Documents and become usable by mfa
