### ISSUE TITLE
Add pip as a secondary installation method.

### ISSUE THREAD

**Issue by Yasand123** [jasonppy/VoiceCraft#27]
Conda is not available on all systems. Pip requirements.txt would be nice.
Thank you.

**Comment by gibru** [comment]
Have you tried [Miniconda](https://docs.anaconda.com/free/miniconda/miniconda-install/)? Can be installed on Windows, Mac and Linux.

Can't speak for Windows and Mac, but on Linux once you have it installed, just activate the env:

- `source minicondalocation/bin/activate` (e.g. in home: `source ~/miniconda3/bin/activate`
- clone VoiceCraft repo and `cd VoiceCraft`
- look for the file `environment.yml` (it's similar to requirements.txt but for sharing conda environments)
- make sure you have your conda env (base) active and that you're inside the VoiceCraft folder and then install the requirements:
   - `conda env create -f environment.yml`

This will create a conda voicecraft env (which you can activate with `conda activate voicecraft` with all the requirements installed).

**Comment by amirvenus** [comment]
> > Have you tried [Miniconda]
> 
> Just set it up. Thank you. Now I only have to figure out how to run it.

Would you be great if you could please share the instructions to run on Apple SoC. 

Thanks1
