### ISSUE TITLE
espeak not working as backend on Windows OS

### ISSUE THREAD

**Issue by ZeroHackz** [jasonppy/VoiceCraft#28]
hi there,

Thanks for open sourcing this, I have everything installed and building perfectly. But espeak isn't supported on windows, is there a way to use a different backend for the text tokenizer?  I've tried nltk and failed :( 

These two lines:
```
text_tokenizer = TextTokenizer(backend="espeak")
audio_tokenizer = AudioTokenizer(signature=encodec_fn)  # Will also put the neural codec model on GPU
```

Everything else is working perfectly: 
![image](https://github.com/jasonppy/VoiceCraft/assets/15729496/13eadf45-f42e-4a3e-bbb1-cb7dcb479014)

**Comment by bbecausereasonss** [comment]
Alot of the installation instructions don't work for windows because apt-get is not a conda/windows cdmlet

**Comment by jasonppy** [comment]
try quickstart with docker, should work for windows https://github.com/jasonppy/VoiceCraft?tab=readme-ov-file#quickstart

**Comment by sangfrois** [comment]
https://github.com/bootphon/phonemizer/issues/44

**Comment by ZeroHackz** [comment]
> try quickstart with docker, should work for windows https://github.com/jasonppy/VoiceCraft?tab=readme-ov-file#quickstart

will do thanks, I'll close this issue.
