### ISSUE TITLE
Is it possible to run this without docker?

### ISSUE THREAD

**Issue by trollkotze** [jasonppy/VoiceCraft#31]
I get this error:
> docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
I blame docker.

Why would I need docker for this? What purpose does it serve?

**Comment by trollkotze** [comment]
Okay, I had to follow this: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
Now it werks.

This from README was not enough: ```sudo apt-get install -y nvidia-container-toolkit-base```

Still, I don't know what the purpose of docker is here.

**Comment by jasonppy** [comment]
Thanks. Everyone has a different setup, and some people find docker to be more helpful. I have updated readme to make it more clear that there are two ways to run tts inference
