### ISSUE TITLE
gradio port

### ISSUE THREAD

**Issue by friendlyFriend4000** [jasonppy/VoiceCraft#35]
I did not like having to mess with jupyter and having to run whisper separately, so I made a gradio version. Will submit pull request eventually. you can try it out here for now.
note that the conda env is slightly different in my fork 
https://github.com/friendlyFriend4000/VoiceCraft

![image](https://github.com/jasonppy/VoiceCraft/assets/127642970/00fcb640-1822-44a2-aa58-1993c8a8611e)

**Comment by jasonppy** [comment]
Thanks! Looking forward to it!

**Comment by SKanav483** [comment]
Can you make a Colab Notebook for this?

**Comment by JMLLR1** [comment]
@friendlyFriend4000 thanks for doing this! I have actually problems in using it (ubuntu 22-04). I get errors like:

`WARNING:phonemizer:words count mismatch on 100.0% of the lines (1/1)`

`RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size`

I am happy in collaborating with you to test and sort out problems like this!
Maybe we need to prepare some more instructions about installing and using is ?

**Comment by friendlyFriend4000** [comment]
> @friendlyFriend4000 thanks for doing this! I have actually problems in using it (ubuntu 22-04). I get errors like:
> 
> `WARNING:phonemizer:words count mismatch on 100.0% of the lines (1/1)`
> 
> `RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size`
> 
> I am happy in collaborating with you to test and sort out problems like this! Maybe we need to prepare some more instructions about installing and using is ?

you can ignore the first error. For the second one I think that your cut off timing slightly beyond the 'expected' transcript. tray decreasing the cut off timing a couple miliseconds

**Comment by friendlyFriend4000** [comment]
> Sorry to bother you again, but the "Output Audio generated" is between 0 to 2 seconds and just scrambled words. probably I am the problem and not doing something i shold do..

there is a complete better version of a gradio implementation on a pr right now
