### ISSUE TITLE
How to install mfa's english_us_arpa, I tried to run commond "mfa model download dictionary english_us_arpa" and "mfa model download acoustic english_us_arpa" with github token, but it doesn't work.

### ISSUE THREAD

**Issue by WoBuChiTang** [jasonppy/VoiceCraft#45]

**Comment by friendlyFriend4000** [comment]
You need to run it in your console in your conda env activated

**Comment by WoBuChiTang** [comment]
> You need to run it in your console in your conda env activated

I did exactly as what you said, but it always does work, even though it didn't put any error.

**Comment by friendlyFriend4000** [comment]
> > You need to run it in your console in your conda env activated
> 
> I did exactly as what you said, but it always does work, even though it didn't put any error.

make sure that you ran this command prior. it installs mfa 
`conda install -c conda-forge montreal-forced-aligner=2.2.17 openfst=1.8.2 kaldi=5.5.1068`

**Comment by WoBuChiTang** [comment]
> > > You need to run it in your console in your conda env activated
> > 
> > 
> > I did exactly as what you said, but it always does work, even though it didn't put any error.
> 
> make sure that you ran this command prior. it installs mfa `conda install -c conda-forge montreal-forced-aligner=2.2.17 openfst=1.8.2 kaldi=5.5.1068`

Thank you, of course I already installed these environments. Now I solve this problem by another way.
