### ISSUE TITLE
PostgreSQL/pgvector requirement?

### ISSUE THREAD

**Issue by 3dluvr** [jasonppy/VoiceCraft#48]
Is the full blown Postgres really needed for this, especially for non-cloud local system executing, and couldn't it be simplified with something like SQLite-VSS (https://github.com/asg017/sqlite-vss)?

**Comment by jasonppy** [comment]
I think this is required by montreal-forced-alignment (MFA) tool. But MFA is not really required, as there are many other forced-alignment tool that can be used. Please see https://github.com/jasonppy/VoiceCraft/issues/44#issuecomment-2029843714
