### ISSUE TITLE
Add option for fp16 kv cache

### ISSUE THREAD

**Issue by DeuceOfClubs** [jasonppy/VoiceCraft#51]
fp16 kv cache would greatly reduce memory usage without significant loss of quality.

**Comment by DeuceOfClubs** [comment]
works on my machine:
![image](https://github.com/jasonppy/VoiceCraft/assets/52089444/c843e98b-c193-427a-8f77-f23f539c50a4)

**Comment by Ph0rk0z** [comment]
Where else did you change it? I added both model.half and changed the float32s to float16s. The memory can still spike.
