### ISSUE TITLE
Few questions about the paper. [Encodec;inference speed; model parameters]

### ISSUE THREAD

**Issue by taras-sereda** [jasonppy/VoiceCraft#7]
Hi @jasonppy , great work and samples, thanks for sharing the code!

Introduction of causal masking for TTS - is an elegant approach for contextualization. Bravo!

I'm curious about few aspects of your work at the moment:

1. Did you train Encodec as well? To my knowledge the parameters are released too. But looking into your code, it seams that you  trained it too. Now I wonder what might be a reason for this. A hypothesis: no parameters for 16 kHz sampling rate?
2. When it comes to inference you mention that you run it multiple times. Can you share inference speed for say 10 seconds long utterance on 820M model?
3. Is there any estimate when model parameters will be released?

Have a good one!
Best, Taras

**Comment by jasonppy** [comment]
Thanks!

> 1. Did you train Encodec as well? To my knowledge the parameters are released too. But looking into your code, it seams that you trained it too. Now I wonder what might be a reason for this. A hypothesis: no parameters for 16 kHz sampling rate?
Yes we trained Encodec as well. We will also open source the trained encodec

> 2. When it comes to inference you mention that you run it multiple times. Can you share inference speed for say 10 seconds long utterance on 820M model?
for the 830M model, the generation time is faster than real time for 10 seconds long utterance on a A40 GPU, more details will be added to the camera-ready paper

> 3. Is there any estimate when model parameters will be released?
Model parameters will be released by the end of this month.

**Comment by taras-sereda** [comment]
Thanks, looking forwards to seem more details!

**Comment by thivux** [comment]
@jasonppy  hi, can you explain why you chose to retrain encodec instead of using the released model? is 8 codebooks too much?
