### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by WoBuChiTang** [jasonppy/VoiceCraft#84]
hello, Im training on part xl of gigaspeech using 4*A100 80G, still report cuda out of memory. how to fix it?

**Comment by jasonppy** [comment]
decrease `max_num_tokens` or increase `gradient_accumulation_steps`

**Comment by truedat101** [comment]
Hi - to apply the above is this batch_size and max_len ?   Noting, I was unable to fix OOM on small GPUs using the prescribed methods: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512' (fill in a value for the mb), or export CUDA_VISIBLE_DEVICES=0,1,2,3 (with chosen device IDs).    I can confirm altering the batch_size and max_len has allowed my initial training to proceed.

**Comment by WoBuChiTang** [comment]
> Hi - to apply the above is this batch_size and max_len ? Noting, I was unable to fix OOM on small GPUs using the prescribed methods: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512' (fill in a value for the mb), or export CUDA_VISIBLE_DEVICES=0,1,2,3 (with chosen device IDs). I can confirm altering the batch_size and max_len has allowed my initial training to proceed.

restrict audio length less than 16s, finally fix this problem

**Comment by yoesak** [comment]
Hi @WoBuChiTang  I'm experiencing the same OOM when training, so I adjust max_num_tokens to 30000, and filter the gigaspeech xs dataset that has only max. 16s length when generate the encodec, and now I got 

AssertionError: Caught AssertionError in DataLoader worker process 3 when I run z_script/e380M.sh,  do you have any clue?

Or how do you generate validation.txt and train.txt for gigaspeech xs dataset ?

**Comment by thivux** [comment]
@WoBuChiTang hi, i need to train this model on a long audio dataset (up to 20 second long), curious what's the max `max_num_tokens` you were able to pull off with your long dataset using 4*A100 80G.

**Comment by WoBuChiTang** [comment]
> @WoBuChiTang hi, i need to train this model on a long audio dataset (up to 20 second long), curious what's the max `max_num_tokens` you were able to pull off with your long dataset using 4*A100 80G.

max_num_tokens: 35000, because the later the more memory use. for you question, i recommend 30000 or 20000
